services:
  productservice:
    image: productservice:v1
    ports:
      - "5001:8080"

  customerservice:
    image: customerservice:v1
    ports:
      - "5002:8080"

  orderservice:
    image: orderservice:v1
    ports:
      - "5003:8080"
    depends_on:
      - productservice
      - customerservice
