replicaCount: 1

image:
  repository: rajendranegi/productwebapp
  tag: v2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  PRODUCT_API_URL: "http://productservice:8080/products"

resources: {}
