global:
  namespace: dev
ingress:
  host: shop.dev.ecommerce-demo1.com
productservice:
  replicaCount: 1
  image:
    repository: rajendranegi/productservice
    tag: v2
  service:
    port: 8080

customerservice:
  replicaCount: 1
  image:
    repository: rajendranegi/customerservice
    tag: v1
  service:
    port: 8080

orderservice:
  replicaCount: 1
  image:
    repository: rajendranegi/orderservice
    tag: v3
  service:
    port: 8080
