global:
  namespace: default
ingress:
  hosts:
    - dev.ecommerce.local
  paths:
    - path: /
      service: productwebapp
      port: 8080
    - path: /products
      service: productservice
      port: 8080
    - path: /customers
      service: customerservice
      port: 8080
    - path: /orders
      service: orderservice
      port: 8080
    - path: /healthz
      service: productservice
      port: 8080
