global:
  namespace: prod

product-service:
  replicaCount: 4
  image:
    repository: rajendranegi/productservice
    tag: v1
  service:
    port: 8080

customer-service:
  replicaCount: 4
  image:
    repository: rajendranegi/customerservice
    tag: v1
  service:
    port: 8080

order-service:
  replicaCount: 4
  image:
    repository: rajendranegi/orderservice
    tag: v1
  service:
    port: 8080
