global:
  namespace: uat

productservice:
  replicaCount: 0
  image:
    repository: rajendranegi/productservice
    tag: v1
  service:
    port: 8080

customerservice:
  replicaCount: 0
  image:
    repository: rajendranegi/customerservice
    tag: v1
  service:
    port: 8080

orderservice:
  replicaCount: 0
  image:
    repository: rajendranegi/orderservice
    tag: v1
  service:
    port: 8080
